The first question rises is 
- # How do we Handle the text data in Numeric Model? 

In [32]:
import pandas as pd

df = pd.read_csv("homeprices.csv")
df.head(10)

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000
5     west windsor  2600  585000
6     west windsor  2800  615000
7     west windsor  3300  650000
8     west windsor  3600  710000
9      robinsville  2600  575000

In [34]:
dummies = pd.get_dummies(df.town)
dummies

monroe township  robinsville  west windsor
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

In [36]:
merged = pd.concat([df,dummies],axis = 'columns')
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000             True        False         False
1   monroe township  3000  565000             True        False         False
2   monroe township  3200  610000             True        False         False
3   monroe township  3600  680000             True        False         False
4   monroe township  4000  725000             True        False         False
5      west windsor  2600  585000            False        False          True
6      west windsor  2800  615000            False        False          True
7      west windsor  3300  650000            False        False          True
8      west windsor  3600  710000            False        False          True
9       robinsville  2600  575000            False         True         False
10      robinsville  2900  600000            False         True         False
11      robinsville  3100  620000            False         True         False
12      robinsville  3600  695000            False         True         False

In [38]:
merged.drop(columns=['town'],axis = 1)

area   price  monroe township  robinsville  west windsor
0   2600  550000             True        False         False
1   3000  565000             True        False         False
2   3200  610000             True        False         False
3   3600  680000             True        False         False
4   4000  725000             True        False         False
5   2600  585000            False        False          True
6   2800  615000            False        False          True
7   3300  650000            False        False          True
8   3600  710000            False        False          True
9   2600  575000            False         True         False
10  2900  600000            False         True         False
11  3100  620000            False         True         False
12  3600  695000            False         True         False

In [40]:
merged.head(10)

town  area   price  monroe township  robinsville  west windsor
0  monroe township  2600  550000             True        False         False
1  monroe township  3000  565000             True        False         False
2  monroe township  3200  610000             True        False         False
3  monroe township  3600  680000             True        False         False
4  monroe township  4000  725000             True        False         False
5     west windsor  2600  585000            False        False          True
6     west windsor  2800  615000            False        False          True
7     west windsor  3300  650000            False        False          True
8     west windsor  3600  710000            False        False          True
9      robinsville  2600  575000            False         True         False

Out of the Dummy columns generated we have to mandatorily drop either one of the dummy variable column since it may create the multicollinearity in the dataframe and that can lead to the bias while developing a Machine Learning Model.


In [43]:
final = merged.drop(columns=['town','west windsor'],axis = 1)
final

area   price  monroe township  robinsville
0   2600  550000             True        False
1   3000  565000             True        False
2   3200  610000             True        False
3   3600  680000             True        False
4   4000  725000             True        False
5   2600  585000            False        False
6   2800  615000            False        False
7   3300  650000            False        False
8   3600  710000            False        False
9   2600  575000            False         True
10  2900  600000            False         True
11  3100  620000            False         True
12  3600  695000            False         True

In [45]:
final.head()

area   price  monroe township  robinsville
0  2600  550000             True        False
1  3000  565000             True        False
2  3200  610000             True        False
3  3600  680000             True        False
4  4000  725000             True        False

In [47]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [49]:
X = final.drop('price',axis=1)
X

area  monroe township  robinsville
0   2600             True        False
1   3000             True        False
2   3200             True        False
3   3600             True        False
4   4000             True        False
5   2600            False        False
6   2800            False        False
7   3300            False        False
8   3600            False        False
9   2600            False         True
10  2900            False         True
11  3100            False         True
12  3600            False         True

In [51]:
y = final.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [53]:
model.fit(X,y)

LinearRegression()

In [55]:
model.predict([[2800,0,1]]) # In Robinsville

C:\Users\yoges\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590775.63964739])

In [57]:
model.predict([[3400,0,0]]) # For west windsor

C:\Users\yoges\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([681241.66845839])

In [61]:
model.score(X,y) # Accuracy of the Model

0.9573929037221873

In [128]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [130]:
dfle = df
dfle.town = le.fit_transform(dfle.town)

In [132]:
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [134]:
X = dfle[['town','area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

y = dfle.price
y

In [137]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [139]:
import numpy as np
X_town = ohe.fit_transform(X[:,[0]]).toarray()
X  = np.concatenate((X_town, X[:,1:]),axis=1)
X

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [141]:
X = X[:,1:]
X

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [143]:
model.fit(X,y)

LinearRegression()

In [151]:
model.predict([[1,0,2800]])

array([590775.63964739])

In [153]:
model.predict([[0,1,3400]])

array([681241.6684584])