In [37]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0]) # 10 labels for the reviews 1- +ve review, 0 - -ve review

How Keras embedding works?

In [38]:
one_hot("amazing restaurant",30) 
#("review", vocabulary size) 
# gives random unique numbers

[7, 24]

In [39]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[25, 13],
 [7, 24],
 [9, 12],
 [23, 6, 26],
 [7, 17, 7],
 [14, 13],
 [14, 17, 14],
 [23, 28],
 [23, 1],
 [8, 2]]

In [40]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post') # padding = post means pad the zeros at the end
print(padded_reviews)

[[25 13  0]
 [ 7 24  0]
 [ 9 12  0]
 [23  6 26]
 [ 7 17  7]
 [14 13  0]
 [14 17 14]
 [23 28  0]
 [23  1  0]
 [ 8  2  0]]


In [41]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length = max_length, name="embedding")) # 1st layer is embedding layer
# vocab_size = 30, embeded_vector_size = 4
model.add(Flatten())
model.add(Dense(1, activation='sigmoid')) # 1 Neuron Sigmoid Actuvation function at the end (Dense layer)

c:\Users\yoges\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [42]:
X = padded_reviews
y = sentiment

In [43]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# binary_crossentropy - output is one or zero (Sentiment good/bad)
print(model.summary())

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_4 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [44]:
model.fit(X,y, epochs=50, verbose =0)

In [45]:
loss,accuracy = model.evaluate(X,y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 1.0000 - loss: 0.6334


1.0

In [46]:
weights = model.get_layer('embedding').get_weights()[0]
weights


array([[-0.00831589, -0.04360425, -0.00430328,  0.03789648],
       [ 0.05013084,  0.03785925,  0.03663841, -0.02670918],
       [ 0.03965819,  0.07077266,  0.02557956, -0.042169  ],
       [-0.04650283, -0.02303783, -0.00072253, -0.00194498],
       [ 0.03117701,  0.02767018, -0.01680509,  0.0134544 ],
       [ 0.02917044, -0.03146726, -0.03846539, -0.04298198],
       [-0.08675996, -0.07621367, -0.05092351,  0.07224248],
       [-0.00686096, -0.04279613, -0.06426432, -0.04111452],
       [-0.01519565,  0.08292994,  0.09233502,  0.08289942],
       [ 0.00771751, -0.05496941, -0.05979995, -0.09931897],
       [-0.00196296, -0.04018726, -0.03548612,  0.04318837],
       [ 0.035467  , -0.03558251,  0.0065129 ,  0.02806046],
       [-0.02358295, -0.08124071, -0.01597411,  0.01598638],
       [ 0.02485964,  0.0041354 , -0.04520279, -0.04204383],
       [ 0.03064517,  0.00387064,  0.07119129,  0.09839614],
       [ 0.01566635,  0.04976871,  0.03149552, -0.03380835],
       [-0.04468112,  0.

In [35]:
len(weights)

30

In [47]:
weights[25]

array([ 0.03247677, -0.03357354, -0.04859487, -0.07049038], dtype=float32)

In [48]:
weights[13]

array([ 0.02485964,  0.0041354 , -0.04520279, -0.04204383], dtype=float32)

In [49]:
weights[12]

array([-0.02358295, -0.08124071, -0.01597411,  0.01598638], dtype=float32)