In [2]:
import nltk

In [3]:
!pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com


In [4]:
nltk.download('book')

[nltk_data] Downloading collection 'book'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\yoges\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package brown to
[nltk_data]    |     C:\Users\yoges\AppData\Roaming\nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package chat80 to
[nltk_data]    |     C:\Users\yoges\AppData\Roaming\nltk_data...
[nltk_data]    |   Package chat80 is already up-to-date!
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     C:\Users\yoges\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package conll2000 to
[nltk_data]    |     C:\Users\yoges\AppData\Roaming\nltk_data...
[nltk_data]    |   Package conll2000 is already up-to-date!
[nltk_data]    | Downloading package conll2002 to
[nltk_data]    |     C:\Users\yoges\AppData\R

True

In [5]:
nltk.download('puket')

[nltk_data] Error loading puket: Package 'puket' not found in index


False

In [6]:
from nltk.book import *

*** Introductory Examples for the NLTK Book ***
Loading text1, ..., text9 and sent1, ..., sent9
Type the name of the text or sentence to view it.
Type: 'texts()' or 'sents()' to list the materials.
text1: Moby Dick by Herman Melville 1851
text2: Sense and Sensibility by Jane Austen 1811
text3: The Book of Genesis
text4: Inaugural Address Corpus
text5: Chat Corpus
text6: Monty Python and the Holy Grail
text7: Wall Street Journal
text8: Personals Corpus
text9: The Man Who Was Thursday by G . K . Chesterton 1908


In [7]:
texts()

text1: Moby Dick by Herman Melville 1851
text2: Sense and Sensibility by Jane Austen 1811
text3: The Book of Genesis
text4: Inaugural Address Corpus
text5: Chat Corpus
text6: Monty Python and the Holy Grail
text7: Wall Street Journal
text8: Personals Corpus
text9: The Man Who Was Thursday by G . K . Chesterton 1908


In [8]:
text1

<Text: Moby Dick by Herman Melville 1851>

In [9]:
text1

<Text: Moby Dick by Herman Melville 1851>

In [10]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [11]:
text = "my name is harish nandhan, i used to attend class for data science, big data and data analytics !!!"

In [12]:
word_tokenize(text)

['my',
 'name',
 'is',
 'harish',
 'nandhan',
 ',',
 'i',
 'used',
 'to',
 'attend',
 'class',
 'for',
 'data',
 'science',
 ',',
 'big',
 'data',
 'and',
 'data',
 'analytics',
 '!',
 '!',
 '!']

In [13]:
sent_tokenize(text)

['my name is harish nandhan, i used to attend class for data science, big data and data analytics !',
 '!',
 '!']

In [14]:
from nltk.corpus import stopwords



In [15]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\yoges\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [16]:
set(stopwords.words('english'))

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [17]:
text.lower()

'my name is harish nandhan, i used to attend class for data science, big data and data analytics !!!'

In [18]:
stop_Words = set(stopwords.words('english'))

In [19]:
word_tokenize(text)

['my',
 'name',
 'is',
 'harish',
 'nandhan',
 ',',
 'i',
 'used',
 'to',
 'attend',
 'class',
 'for',
 'data',
 'science',
 ',',
 'big',
 'data',
 'and',
 'data',
 'analytics',
 '!',
 '!',
 '!']

In [20]:
# Removal of Stop words
[i for i in word_tokenize(text.lower()) if i.lower() not in stop_Words]

['name',
 'harish',
 'nandhan',
 ',',
 'used',
 'attend',
 'class',
 'data',
 'science',
 ',',
 'big',
 'data',
 'data',
 'analytics',
 '!',
 '!',
 '!']

In [21]:
text

'my name is harish nandhan, i used to attend class for data science, big data and data analytics !!!'

In [31]:
text1 = "i am teaching in my classes"

In [32]:
# stemming - converting the word into the root word

from nltk.stem import PorterStemmer

stemring = PorterStemmer()
for i in word_tokenize(text1):
    print(stemring.stem(i))


i
am
teach
in
my
class


In [33]:
# lemmatization - 
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\yoges\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [34]:
text_token = word_tokenize(text1)
text_token

['i', 'am', 'teaching', 'in', 'my', 'classes']

In [35]:
for i in text_token:
    print(WordNetLemmatizer().lemmatize(i))

i
am
teaching
in
my
class


In [36]:
stopwords.words('tamil')

['அங்கு',
 'அங்கே',
 'அடுத்த',
 'அதனால்',
 'அதன்',
 'அதற்கு',
 'அதிக',
 'அதில்',
 'அது',
 'அதே',
 'அதை',
 'அந்த',
 'அந்தக்',
 'அந்தப்',
 'அன்று',
 'அல்லது',
 'அவன்',
 'அவரது',
 'அவர்',
 'அவர்கள்',
 'அவள்',
 'அவை',
 'ஆகிய',
 'ஆகியோர்',
 'ஆகும்',
 'இங்கு',
 'இங்கே',
 'இடத்தில்',
 'இடம்',
 'இதனால்',
 'இதனை',
 'இதன்',
 'இதற்கு',
 'இதில்',
 'இது',
 'இதை',
 'இந்த',
 'இந்தக்',
 'இந்தத்',
 'இந்தப்',
 'இன்னும்',
 'இப்போது',
 'இரு',
 'இருக்கும்',
 'இருந்த',
 'இருந்தது',
 'இருந்து',
 'இவர்',
 'இவை',
 'உன்',
 'உள்ள',
 'உள்ளது',
 'உள்ளன',
 'எந்த',
 'என',
 'எனக்',
 'எனக்கு',
 'எனப்படும்',
 'எனவும்',
 'எனவே',
 'எனினும்',
 'எனும்',
 'என்',
 'என்ன',
 'என்னும்',
 'என்பது',
 'என்பதை',
 'என்ற',
 'என்று',
 'என்றும்',
 'எல்லாம்',
 'ஏன்',
 'ஒரு',
 'ஒரே',
 'ஓர்',
 'கொண்ட',
 'கொண்டு',
 'கொள்ள',
 'சற்று',
 'சிறு',
 'சில',
 'சேர்ந்த',
 'தனது',
 'தன்',
 'தவிர',
 'தான்',
 'நான்',
 'நாம்',
 'நீ',
 'பற்றி',
 'பற்றிய',
 'பல',
 'பலரும்',
 'பல்வேறு',
 'பின்',
 'பின்னர்',
 'பிற',
 'பிறகு',
 'பெரும்',
 'பேர்',
 'போது',
 

In [37]:
from nltk.stem import LancasterStemmer

lanc = LancasterStemmer()
lanc.stem('running')

'run'

In [38]:
for i in text_token:
    print(lanc.stem(i))

i
am
teach
in
my
class


In [40]:
# POS Tagging

from nltk.tag import pos_tag
pos_tag(["apple","nandhan","running","!"])

[('apple', 'NN'), ('nandhan', 'NN'), ('running', 'VBG'), ('!', '.')]

Exercise
- Create a Python function summarize_text_features(text_corpus: List[str]) -> Dict that performs the following

In [2]:
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize # Tokenization

# feature extraction
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Word embeddings
from gensim.models import Word2Vec

# Numerical and Data Handling
import numpy as np
import pandas as pd

# For displaying results
from pprint import pprint

In [3]:
nltk.download('all')
nltk.download('stopwords')


[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\yoges\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\yoges\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\yoges\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\yoges\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\yoges\AppData\Roaming\nltk_data...
[

True

In [4]:
def preprocess_text(text_corpus):
    stop_words = set(stopwords.words('english'))
    cleaned_corpus = []

    for sentence in text_corpus:
        # Lowercase
        sentence = sentence.lower()
        # Remove punctuation
        sentence = sentence.translate(str.maketrans('', '', string.punctuation))
        # Tokenize
        tokens = word_tokenize(sentence)
        # Remove stopwords
        filtered_tokens = [word for word in tokens if word not in stop_words]
        cleaned_corpus.append(filtered_tokens)

    return cleaned_corpus


In [5]:
text_corpus = [
    "The cat sat on the mat.",
    "Dogs are loyal and friendly animals.",
    "Cats and dogs are popular pets.",
    "I love my cute little kitten.",
    "My dog loves to play fetch in the park."
]

cleaned_corpus = preprocess_text(text_corpus)
pprint(cleaned_corpus)


[['cat', 'sat', 'mat'],
 ['dogs', 'loyal', 'friendly', 'animals'],
 ['cats', 'dogs', 'popular', 'pets'],
 ['love', 'cute', 'little', 'kitten'],
 ['dog', 'loves', 'play', 'fetch', 'park']]


In [6]:
def build_vocabulary(cleaned_corpus):
    vocab = sorted(set(word for doc in cleaned_corpus for word in doc))
    word_to_index = {word: idx for idx, word in enumerate(vocab)}
    return vocab, word_to_index

def one_hot_encode(cleaned_corpus, word_to_index):
    one_hot_vectors = []

    for doc in cleaned_corpus:
        vector = [0] * len(word_to_index)
        for word in doc:
            if word in word_to_index:
                vector[word_to_index[word]] = 1
        one_hot_vectors.append(vector)
    
    return np.array(one_hot_vectors)


In [7]:
vocab, word_to_index = build_vocabulary(cleaned_corpus)
print("Vocabulary:", vocab)

one_hot_matrix = one_hot_encode(cleaned_corpus, word_to_index)
print("\nOne-Hot Encoded Matrix (Doc x Vocab):")
print(one_hot_matrix)


Vocabulary: ['animals', 'cat', 'cats', 'cute', 'dog', 'dogs', 'fetch', 'friendly', 'kitten', 'little', 'love', 'loves', 'loyal', 'mat', 'park', 'pets', 'play', 'popular', 'sat']

One-Hot Encoded Matrix (Doc x Vocab):
[[0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1]
 [1 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 1 0 0 1 0 1 0 0]]
