In [6]:
# Using requests library for embeddings
import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/alpha/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNmQwZDlkMC1mNzgzLTQ3MTItOTBlYy1jYjAwZGUzNjQ5ZWMiLCJlbWFpbCI6ImhhcmlzaG5hbmRoYW4wMkBnbWFpbC5jb20iLCJpYXQiOjE3NDYzMzUzOTIsImV4cCI6MTc3Nzg3MTM5Mn0.3Q5m_zcpqTcsuwQ3prMjhFuAYa_Fy1BLapaCv93DRQ8"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    # Convert to numpy array for vector operations
    embedding = np.array(data['data'][0]['embedding'])
    
    print(f"Generated embedding with shape: {embedding.shape}")
    print(f"First 5 values: {embedding[:5]}")
    
    # Example: Calculate vector norm
    norm = np.linalg.norm(embedding)
    print(f"Vector norm: {norm}")
    
    return embedding


In [2]:
generate_embeddings()

Generated embedding with shape: (1536,)
First 5 values: [-0.03244253 -0.00839565 -0.06356495 -0.04268333  0.04704366]
Vector norm: 1.000000029660755


array([-0.03244253, -0.00839565, -0.06356495, ..., -0.00225143,
        0.05896459, -0.03152246])

- Where we are going to store the embeddings generated for the input?
- This is where the Vector DB comes into picture.

In [8]:
data1 = generate_embeddings("my name is harish nandhan")


Generated embedding with shape: (1536,)
First 5 values: [-0.00495937 -0.03673173 -0.03070396  0.00419413 -0.02893801]
Vector norm: 1.0000000480938225


In [9]:
data1

array([-0.00495937, -0.03673173, -0.03070396, ..., -0.00454732,
        0.00670472, -0.03392976])

In [10]:
data2 = generate_embeddings("harish nandhan learns the generative ai in summer")

Generated embedding with shape: (1536,)
First 5 values: [-0.02770582 -0.00069617  0.07564048  0.01759141  0.00182284]
Vector norm: 1.0000000360659889


In [ ]:
#data2

array([-0.02770582, -0.00069617,  0.07564048, ..., -0.02239255,
        0.00179563, -0.0167336 ])

In [13]:
# How actually the search happens here?

# Euclidean Distance
import numpy as np
data1 , data2
# Formula for Cosine Similarity
cosine_similarity = np.dot(data1,data2)/np.linalg.norm(data1)*np.linalg.norm(data2)
cosine_similarity

0.43941448438239317

In [ ]:
def cosine_similarity_fn(data_a,data_b):
    cosine_similarity = np.dot(data_a,data_b)/np.linalg.norm(data_a)*np.linalg.norm(data_b)
    return cosine_similarity

In [17]:
cosine_distance = 1 - cosine_similarity
cosine_distance

0.5605855156176068

In [15]:
data3 = generate_embeddings("people call me by my name harish nandhan")

Generated embedding with shape: (1536,)
First 5 values: [ 0.03016465 -0.05344609 -0.02778589  0.02776059 -0.03385931]
Vector norm: 1.0000000298615765


In [19]:
data1, data2, data3

(array([-0.00495937, -0.03673173, -0.03070396, ..., -0.00454732,
         0.00670472, -0.03392976]),
 array([-0.02770582, -0.00069617,  0.07564048, ..., -0.02239255,
         0.00179563, -0.0167336 ]),
 array([ 0.03016465, -0.05344609, -0.02778589, ..., -0.00596587,
         0.00145193, -0.01895413]))

In [ ]:
1 - cosine_similarity_fn(data1,data2) # Here Data 1 and Data 3 is more so this is less similar compared to data1, data3 

0.5605855156176068

In [ ]:
1 - cosine_similarity_fn(data1,data3) # Here Data 1 and Data 3 is very less so this is more similar

0.16302638041024153