In [1]:
!pip install langchain faiss-cpu tiktoken requests

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   ---------------------------------------- 1.0/1.0 MB 24.2 MB/s eta 0:00:00
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 59.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/15.0 MB ? eta -:--:--
   ------------------- -------------------- 7.3/15.0 MB 41.2 MB/s eta 0:00:01
   ------------------------------ --------- 11.5/15.0 MB 34.4 MB/s eta 0:00:01
   ---------------------------------------- 15.0/15.0 MB 24.8 MB/s eta 0:00:00
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   -------------------------------- ------- 10.5/12.9 MB 46.7 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 50.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/894.0 kB ? eta -:--:--
   ---------------------------

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorboard 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 6.31.1 which is incompatible.
tensorflow 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 6.31.1 which is incompatible.


In [2]:
from langchain.embeddings.base import Embeddings
from langchain.llms.base import LLM
from typing import List, Dict, Any
import requests
import numpy as np
import faiss
import os


In [3]:
# Using requests library for embeddings
import requests
import numpy as np

def generate_embeddings(text: str):
    url = "https://api.euron.one/api/v1/euri/alpha/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNmQwZDlkMC1mNzgzLTQ3MTItOTBlYy1jYjAwZGUzNjQ5ZWMiLCJlbWFpbCI6ImhhcmlzaG5hbmRoYW4wMkBnbWFpbC5jb20iLCJpYXQiOjE3NDgzODIzNTMsImV4cCI6MTc3OTkxODM1M30.4uOCjjuVYPi_SL7MVnIOSOGKMsc8YhmD-aqohvU2Uwk"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()

    # Convert to numpy array for vector operations
    embedding = np.array(data['data'][0]['embedding'])

    return embedding


In [4]:
!pip install euriai

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
INFO: pip is looking at multiple versions of llama-cloud-services to determine which version is compatible with other requirements. This could take a while.
INFO: pip is still looking at multiple versions of llama-cloud-services to determine which version is compatible with other requirements. This could take a while.
   ---------------------------------------- 0.0/7.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.6 MB ? eta -:--:--
   ---- ----------------------------------- 0.8/7.6 MB 1.6 MB/s eta 0:00:05
   ------ --------------------------------- 1.3/7.6 MB 1.9 MB/s eta 0:00:04
   --------- ------------------------------ 1.8/7.6 MB 2.1 MB/s eta 0:00:03
   ------------- -------------------------- 2.6/7.6 MB 2.3 MB/s eta 0:00:03
   ---------------- ----------------------- 3.1/7.6 MB 2.4 MB/s eta 0:00:02
   -----------------

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorboard 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 6.31.1 which is incompatible.
tensorflow 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 6.31.1 which is incompatible.


In [5]:
from euriai import EuriaiClient
def generate_response(prompt):
  client = EuriaiClient(
      api_key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNmQwZDlkMC1mNzgzLTQ3MTItOTBlYy1jYjAwZGUzNjQ5ZWMiLCJlbWFpbCI6ImhhcmlzaG5hbmRoYW4wMkBnbWFpbC5jb20iLCJpYXQiOjE3NDgzODIzNTMsImV4cCI6MTc3OTkxODM1M30.4uOCjjuVYPi_SL7MVnIOSOGKMsc8YhmD-aqohvU2Uwk",
      model="gpt-4.1-nano"  # You can also try: "gemini-2.0-flash-001", "llama-4-maverick", etc.
  )

  response = client.generate_completion(
      prompt= prompt,
      temperature=0.7,
      max_tokens=300
  )

  print(response)
  return response['choices'][0]["message"]["content"]

In [6]:
!pip install -U langchain-community

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   --------------------------------- ------ 2.1/2.5 MB 14.7 MB/s eta 0:00:01
   ---------------------------------------- 2.5/2.5 MB 18.1 MB/s eta 0:00:00

   -------------------------- ------------- 2/3 [langchain-community]
   -------------------------- ------------- 2/3 [langchain-community]
   -------------------------- ------------- 2/3 [langchain-community]
   -------------------------- ------------- 2/3 [langchain-community]
   -------------------------- ------------- 2/3 [langchain-community]
   -------------------------- ------------- 2/3 [langchain-community]
   -------------------------- ------------- 2/3 [langchain-community]
   -------------------------- ------------- 2/3 [langchain-community]
   -------------------------- ------------- 2/3 [langchain-community]
   -------------------------- ------------- 2/3 [langchain-community]
   

In [7]:
!pip install -U langchain langchain-core

In [8]:
from langchain.document_loaders import TextLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter

document = TextLoader(r"C:\Users\yoges\Data_Science_Preparation\Generative AI Learnings\RAG Langchain\data.txt").load()
document


# or
# with open("data.txt","r") as file:
#   text = file.read()

[Document(metadata={'source': 'C:\\Users\\yoges\\Data_Science_Preparation\\Generative AI Learnings\\RAG Langchain\\data.txt'}, page_content="Helping Millions of Students Succeed\nSudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.\n\nIn 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world.\n\n\nThe Entrepreneur and Teacher: Sudhanshu's Dual Legacy\nSudhanshu's journey isn

In [9]:
splitter = RecursiveCharacterTextSplitter(chunk_size=300, chunk_overlap=30)
# break the data into chunks
# if any of the sentence is break into half the overlap will make sure it starts from the base again
docs = splitter.split_documents(document)

In [10]:
len(docs)

31

In [11]:
# Step 2: Convert everything into embeddings and save it into the Vector DB (FAISS)
texts = [doc.page_content for doc in docs]
texts


['Helping Millions of Students Succeed',
 "Sudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students,",
 'Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.',
 'In 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world.',
 "The Entrepreneur and Teacher: Sudhanshu's Dual Legacy",
 "Sudhanshu's journey isn't just one of entrepreneurial success; it's also a story of dedication to teaching. Throughout his caree

In [12]:
embeddings = [generate_embeddings(i).astype('float32') for i in texts]


In [13]:
embeddings

[array([ 0.02873218, -0.03871168,  0.05527106, ..., -0.01516116,
        -0.03901326,  0.00616522], shape=(1536,), dtype=float32),
 array([-0.01364236,  0.00639423,  0.05721121, ..., -0.00413274,
        -0.00975312, -0.00021493], shape=(1536,), dtype=float32),
 array([-0.02204193, -0.00722562,  0.00345266, ..., -0.00756314,
        -0.02643654, -0.00205438], shape=(1536,), dtype=float32),
 array([-0.04330518, -0.05195538,  0.02764536, ..., -0.03267549,
         0.01820879,  0.03354321], shape=(1536,), dtype=float32),
 array([ 0.01671011,  0.01011956,  0.04287479, ..., -0.04371754,
         0.01135734, -0.00684733], shape=(1536,), dtype=float32),
 array([-0.00970297, -0.00214104,  0.0598214 , ..., -0.01701215,
        -0.01090567,  0.00101315], shape=(1536,), dtype=float32),
 array([-0.00568317, -0.01421538,  0.03512035, ..., -0.00705393,
         0.00747801,  0.00206959], shape=(1536,), dtype=float32),
 array([ 0.00620001, -0.03134765,  0.04846245, ...,  0.0006798 ,
        -0.0170516

In [15]:
import faiss
from langchain.vectorstores.faiss import FAISS
from langchain.docstore.document import Document

In [16]:
dimension = embeddings[0].shape[0]
faiss_index = faiss.IndexFlatL2(dimension)

faiss_index.add(np.array(embeddings).astype('float32'))

In [17]:
faiss_index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x7a22d60d0660> >

In [20]:
embeddings

[array([ 0.02873218, -0.03871168,  0.05527106, ..., -0.01516116,
        -0.03901326,  0.00616522], dtype=float32),
 array([-0.01364236,  0.00639423,  0.05721121, ..., -0.00413274,
        -0.00975312, -0.00021493], dtype=float32),
 array([-0.02204193, -0.00722562,  0.00345266, ..., -0.00756314,
        -0.02643654, -0.00205438], dtype=float32),
 array([-0.04330518, -0.05195538,  0.02764536, ..., -0.03267549,
         0.01820879,  0.03354321], dtype=float32),
 array([ 0.01669575,  0.010132  ,  0.04289808, ..., -0.0436881 ,
         0.01136312, -0.00684026], dtype=float32),
 array([-0.00970297, -0.00214104,  0.0598214 , ..., -0.01701215,
        -0.01090567,  0.00101315], dtype=float32),
 array([-0.00568317, -0.01421538,  0.03512035, ..., -0.00705393,
         0.00747801,  0.00206959], dtype=float32),
 array([ 0.00617231, -0.03135141,  0.04851883, ...,  0.00069134,
        -0.01702837,  0.0169778 ], dtype=float32),
 array([ 0.05260113, -0.00281351,  0.01458545, ..., -0.01748176,
       

In [22]:
from langchain.chains import RetrievalQA

In [28]:
document = [Document(page_content=text) for text in texts[:len(embeddings)]]

In [30]:
document

[Document(metadata={}, page_content='Helping Millions of Students Succeed'),
 Document(metadata={}, page_content="Sudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students,"),
 Document(metadata={}, page_content='Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.'),
 Document(metadata={}, page_content='In 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world.'),
 Document(metadata={}, page_content="The Ent

In [34]:
import faiss
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_community.vectorstores import FAISS

faiss_index = faiss.IndexFlatL2(dimension)

vector_store = FAISS(
    embedding_function=generate_embeddings,
    index=faiss_index,
    docstore=InMemoryDocstore(),
    index_to_docstore_id={},
)

vector_store.add_documents(document)

['a3af1924-8143-4b7f-aa94-967b3bd322e2',
 '7110e8a6-78b9-4603-a709-f57aa865f33c',
 '70d4b2e7-0475-4b79-961b-5fead362d099',
 'd676318c-f5fe-4acc-829c-ef30218f8df1',
 '5e9c7cff-450c-41f7-afb8-90b4915513ac',
 'b04100ab-3d7b-4945-a6ca-77616e431da3',
 'ad1daf5c-95b3-4955-9218-a045a40648f9',
 '38f56381-195d-4f70-ae9b-8a483f872b7a',
 '487cf4e7-1f52-4dd5-a4f2-69c56001bc55',
 'dd79735f-6ae1-4bd1-8e58-635a6c4214a5',
 '6b50ec7f-2aa8-4094-bae7-82aa513b98c3',
 '56d10808-c040-4865-9efc-f7b5192def70',
 '78a63101-453f-4ba5-bad5-b29ecfbf322c',
 '1558f704-db54-4893-bc88-9dd2b667d603',
 '5128997f-70ec-4ab7-8211-f6b88f415b7b',
 'c80c4bfc-210e-434e-b94d-417c14dbe28a',
 '11792ed0-8ca5-4d27-b08e-3d2ff3a32c82',
 'f5381dca-db62-4737-a07a-62191f12eb55',
 'ba79a871-88e8-4b99-bf72-2fa61874ebfc',
 '0721c59a-9081-46b5-828b-936c1f108289',
 'b7517de9-547d-4b5d-9dc9-85833ec2209e',
 'ea90da8b-33ba-435c-bfcd-e131b2b98e74',
 '1bae4fdf-d10c-41f4-8f5d-9d6abf2185d2',
 'c25fbdfd-d2b1-44bb-8ab7-abd40c03fc5c',
 '0a0befb5-ef62-

In [36]:
vector_store.save_local("faiss index")

In [37]:
retriever = vector_store.as_retriever(search_kwargs={"k":2})

In [38]:
from euriai import EuriaiLangChainLLM

llm = EuriaiLangChainLLM(
    api_key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNmQwZDlkMC1mNzgzLTQ3MTItOTBlYy1jYjAwZGUzNjQ5ZWMiLCJlbWFpbCI6ImhhcmlzaG5hbmRoYW4wMkBnbWFpbC5jb20iLCJpYXQiOjE3NDYzMzUzOTIsImV4cCI6MTc3Nzg3MTM5Mn0.3Q5m_zcpqTcsuwQ3prMjhFuAYa_Fy1BLapaCv93DRQ8",
    model="gpt-4.1-nano",
    temperature=0.7,
    max_tokens=300
)

print(llm.invoke("Write a poem about time travel."))



In whispers woven through the fabric of night,  
Time’s silent river flows, both swift and slight,  
A voyage spun in threads of yesterday and morrow,  
Where hopes and fears collide, dissolve, and borrow.

A leap beyond the shadowed veil of now,  
To moments lost, to then and future’s vow,  
Where history’s secrets softly intertwine,  
And every choice becomes a sacred line.

Through corridors of what once might have been,  
We chase the echoes of a distant kin,  
A whisper of seconds, a breath so fleet—  
Time’s endless dance, both bitter and sweet.

With every tick, a universe rewrites,  
A flash of dawn, a fall of night’s delights,  
Boundless yet confined within its sway,  
Time travels on, never led astray.

So dream of moments yet to unfold,  
Of stories yet to be told,  
For in the voyage through the ages’ seam,  
Time’s eternal river flows as a dream.


In [41]:
rag_chain = RetrievalQA.from_chain_type(llm = llm,retriever = retriever)
# retrieval has to be extracted from the vector db - faiss we have stored there
# llm - by using an API call / EURI API we can use

In [42]:
rag_chain("who is sudhanshu")

/tmp/ipython-input-42-2566710363.py:1: LangChainDeprecationWarning: The method `Chain.__call__` was deprecated in langchain 0.1.0 and will be removed in 1.0. Use :meth:`~invoke` instead.
  rag_chain("who is sudhanshu")


{'query': 'who is sudhanshu',
 'result': 'Sudhanshu is a person from Jamshedpur, Jharkhand, India, who overcame financial hardships and challenges to pursue education. His story is one of determination and resilience, driven by the belief in the transformative power of education to improve his life and the lives of his family.'}